FROM python:3.13.7-slim-trixie

WORKDIR /app

RUN apt-get update && \
    apt-get install -y build-essential gcc libmariadb-dev libssl-dev libicapapi-dev python3-dev libpq-dev git && \
    rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/kaelthasmanu/SquidStats.git /app

RUN pip install --no-cache-dir -r requirements.txt

# Apply English translations
COPY translate.sh /translate.sh
RUN chmod +x /translate.sh && /translate.sh

EXPOSE 5000
CMD ["python", "app.py"]
