FROM alpine:3.21

RUN apk add --no-cache \
        squid \
        openssl \
        ca-certificates \
        net-tools && \
    mkdir -p /var/log/squid /var/spool/squid /var/run/squid /etc/squid/certs && \
    chown -R squid:squid /var/log/squid /var/spool/squid /var/run/squid /etc/squid/certs

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 3128

ENTRYPOINT ["/entrypoint.sh"]
