FROM alpine:3.21

RUN apk add --no-cache \
        squid \
        openssl \
        ca-certificates

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 3128

ENTRYPOINT ["/entrypoint.sh"]
